Hirings: 

[Provider: 1, Workers Hired: 0]
[Provider: 2, Workers Hired: 0]
[Provider: 3, Workers Hired: 76]
[Provider: 4, Workers Hired: 0]
[Provider: 5, Workers Hired: 0]
[Provider: 6, Workers Hired: 0]
[Provider: 7, Workers Hired: 0]
[Provider: 8, Workers Hired: 0]
[Provider: 9, Workers Hired: 0]
[Provider: 10, Workers Hired: 0]
[Provider: 11, Workers Hired: 0]
[Provider: 12, Workers Hired: 65]
[Provider: 13, Workers Hired: 0]
[Provider: 14, Workers Hired: 62]
[Provider: 15, Workers Hired: 0]
[Provider: 16, Workers Hired: 0]
[Provider: 17, Workers Hired: 0]
[Provider: 18, Workers Hired: 0]
[Provider: 19, Workers Hired: 0]
[Provider: 20, Workers Hired: 46]
[Provider: 21, Workers Hired: 69]
[Provider: 22, Workers Hired: 0]
[Provider: 23, Workers Hired: 61]
[Provider: 24, Workers Hired: 0]
[Provider: 25, Workers Hired: 0]
[Provider: 26, Workers Hired: 0]
[Provider: 27, Workers Hired: 0]
[Provider: 28, Workers Hired: 55]
[Provider: 29, Workers Hired: 34]
[Provider: 30, Workers Hired: 80]
[Provider: 31, Workers Hired: 0]
[Provider: 32, Workers Hired: 0]
[Provider: 33, Workers Hired: 0]
[Provider: 34, Workers Hired: 0]
[Provider: 35, Workers Hired: 0]
[Provider: 36, Workers Hired: 66]
[Provider: 37, Workers Hired: 0]
[Provider: 38, Workers Hired: 63]
[Provider: 39, Workers Hired: 0]
[Provider: 40, Workers Hired: 59]

Objective value: 764706 
