Hirings: 

[Provider: 1, Workers Hired: 0]
[Provider: 2, Workers Hired: 54]
[Provider: 3, Workers Hired: 0]
[Provider: 4, Workers Hired: 0]
[Provider: 5, Workers Hired: 52]
[Provider: 6, Workers Hired: 0]
[Provider: 7, Workers Hired: 50]
[Provider: 8, Workers Hired: 0]
[Provider: 9, Workers Hired: 44]
[Provider: 10, Workers Hired: 0]
[Provider: 11, Workers Hired: 38]
[Provider: 12, Workers Hired: 0]
[Provider: 13, Workers Hired: 0]
[Provider: 14, Workers Hired: 0]
[Provider: 15, Workers Hired: 0]
[Provider: 16, Workers Hired: 26]
[Provider: 17, Workers Hired: 60]
[Provider: 18, Workers Hired: 0]
[Provider: 19, Workers Hired: 58]
[Provider: 20, Workers Hired: 0]
[Provider: 21, Workers Hired: 0]
[Provider: 22, Workers Hired: 0]
[Provider: 23, Workers Hired: 0]
[Provider: 24, Workers Hired: 0]
[Provider: 25, Workers Hired: 52]
[Provider: 26, Workers Hired: 19]
[Provider: 27, Workers Hired: 0]
[Provider: 28, Workers Hired: 0]
[Provider: 29, Workers Hired: 58]
[Provider: 30, Workers Hired: 0]

Objective value: 398955 
